const data={
products:[
    {
        _id:'1',
        name:'fsdfsd  Slim Shirt',
        category:'shirts',
        image:'/images/p1.jpg',
        price:120,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'hight quality product',
    },
    {
        _id:'2',
        name:'Noke Sfds hirt',
        category:'shirts',
        image:'/images/p2.jpg',
        price:586,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'hight quality product',
    },
    {
        _id:'3',
        name:'fdfsdf Slim Shirt',
        category:'shirts',
        image:'/images/p3.jpg',
        price:23,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'hight quality product',
    },
    {
        _id:'4',
        name:'Noffff ke Slim Shirt',
        category:'shirts',
        image:'/images/p4.jpg',
        price:45,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'hight quality product',
    },
    {
        _id:'5',
        name:'ewrtt Slim Shirt',
        category:'shirts',
        image:'/images/p5.jpg',
        price:545,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'hight quality product',
    },
    {
        _id:'6',
        name:'kllll Slim Shirt',
        category:'shirts',
        image:'/images/p6.jpg',
        price:33,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'hight quality product',
    },
],
};
export default data;